---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install tomcat
    yum: name=tomcat state=present
  - name: start tomcat
    service: name=tomcat state=started
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    yum: name=git state=present
  - name: clone a repo
    git: repo=https://https://github.com/Prabir-92/AnsibleDockerproject.git dest=/tmp/mygitrepo1
  - name: build docker file
    command: chdir=/tmp/mygitrepo1 docker build -t prabir92:ansible92 .
  - name: create container
    command: docker run -itd -P prabir92:ansible92

